package com.lyw.greendaotest;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lyw.greendaotest.bean.Dog;
import com.lyw.greendaotest.bean.JoinSheepToUser;
import com.lyw.greendaotest.bean.Sheep;
import com.lyw.greendaotest.bean.User;

import com.lyw.greendaotest.DogDao;
import com.lyw.greendaotest.JoinSheepToUserDao;
import com.lyw.greendaotest.SheepDao;
import com.lyw.greendaotest.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dogDaoConfig;
    private final DaoConfig joinSheepToUserDaoConfig;
    private final DaoConfig sheepDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DogDao dogDao;
    private final JoinSheepToUserDao joinSheepToUserDao;
    private final SheepDao sheepDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dogDaoConfig = daoConfigMap.get(DogDao.class).clone();
        dogDaoConfig.initIdentityScope(type);

        joinSheepToUserDaoConfig = daoConfigMap.get(JoinSheepToUserDao.class).clone();
        joinSheepToUserDaoConfig.initIdentityScope(type);

        sheepDaoConfig = daoConfigMap.get(SheepDao.class).clone();
        sheepDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        dogDao = new DogDao(dogDaoConfig, this);
        joinSheepToUserDao = new JoinSheepToUserDao(joinSheepToUserDaoConfig, this);
        sheepDao = new SheepDao(sheepDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Dog.class, dogDao);
        registerDao(JoinSheepToUser.class, joinSheepToUserDao);
        registerDao(Sheep.class, sheepDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        dogDaoConfig.clearIdentityScope();
        joinSheepToUserDaoConfig.clearIdentityScope();
        sheepDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DogDao getDogDao() {
        return dogDao;
    }

    public JoinSheepToUserDao getJoinSheepToUserDao() {
        return joinSheepToUserDao;
    }

    public SheepDao getSheepDao() {
        return sheepDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
